---
title: "Research"
output: html_document
---
```{=html}
<style>
  /* this just styles the big page title */
  #header h1.title {
    text-align: center;
    font-size: 2.5rem !important;
    margin-top: 0.5rem;
  }
</style>
```

## Dissertation Research
### Habitat specialization and edge effects of soil microbial communities in a fragmented landscape
[Winfrey, Resasco & Fierer, 2025](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecy.70072)
While edge effects caused by habitat fragmentation have been well documented in plants and animals, whether or not soil bacteria, archaea, and fungi exhibit edge effects is an open question. Given the central role of microorganisms as drivers of soil ecosystem services, examining the responses of soil microorganisms to edge effects is important initial step for understanding how soil functioning may be impacted by habitat fragmentation. 

Motivated by this knowledge gap, we used 16S and ITS rRNA gene sequencing to survey the spatial distributions of soil bacteria, archaea, and fungi communities in replicate ~1 hectare open patches surrounded by forested plantation matrix in South Carolina, USA. We discovered that the greater the vegetation contrast between the patch and the matrix, the more pronounced was the microbial turnover across the edge and more distinct were patch and matrix communities. These observed edge effects were driven mostly by taxa that specialized in the open patch or the forested matrix; there were very few taxa that preferred edge habitat. We next explored if phylogeny or life history traits might distinguish taxa that responded to the edge from generalist taxa. We did not find support for our hypotheses that generalist taxa would be more likely to sporulate or have larger genomes (associated with greater metabolic versatility). However, we did find that Chloroflexi and arbuscular mycorrhizal fungi strongly preferred the open patch over matrix or edge habitat, suggesting that they may be particularly vulnerable to fragment edges. 

### The sources and traits of bacteria and fungi found in the near-surface atmosphere
Paper to be submitted soon!

## Other Research
### Do biogeographical 'rules' apply to microorganisms?
[Dickey et al., 2021](https://www.frontiersin.org/journals/ecology-and-evolution/articles/10.3389/fevo.2021.633155/full)
Macroecological 'rules' are a series of patterns that essentially summarize our current understanding of biogeography. Based on centuries of observations of animals and plants, these 'rules' describe the relationships between distribution on the Earth's surface (e.g., latitude, area, temperature) to organismal traits or community assembly and biodiversity. However, our knowledge of if these rules apply to the majority of species on Earth--the largely unseen bacteria, archaea, and fungi--is only now starting to become clear. In this paper, we perform a literature meta-analysis to assess how well microorganisms conform to biogeographical patterns, considering aquatic and terrestrial systems as well as host-assoicated and free-living microbes. Along with Anchal Padukone, I wrote the Island Biogeography section!

### Do male damselflies males use senses other than visual to detect their mates?
[Winfrey & Fincke, 2017](https://www.tandfonline.com/doi/abs/10.1080/13887890.2017.1297259)
Because damselflies are speciose, have radiated recently, and have complex mating behaviors, damselflies are model organisms for studies of sexual selection and sexual conflict. Most of this work to date operates under the assumption that males use only visual cues to detect and identify mates. Our research was the first to test this assumption in the field, finding that males do not orient to females without visual cues. 

### How prevalent is Batrachochytrium dendrobatidis (Bd) among amphibians in Southern Oklahoma?
[Marhanka et al. 2017](https://cameronsiler.com/detection-of-high-prevalence-of-batrachochytrium-dendrobatidis-in-amphibians-from-southern-oklahoma/)
Batrachochytrium dendrobatidis (Bd, often called chytrid for short) has caused massive declines in amphibian populations worldwide. Research supports that the prevalence and lethality of Bd worldwide is on the rise, due to human-mediated spread of the fungus and warmer global temperatures, respectively. However, despite the threat of this fungus and Oklahoma's high amphibian biodiversity, only 4 isolated sites had been sampled for Bd in Oklahoma prior to this work.  For this project, we sampled 14 sites across Southern Oklahoma for frogs and salamanders. All amphibian families, all sampling locations, and 15/18 species were Bd +, although locations and species differed in their pathogen loads.

### Describing a new species of Philippine Slender Skink (Brachymeles bonitae complex)
[Davis et al. 2016](https://cameronsiler.com/additions-to-philippine-slender-skinks-of-the-brachymeles-bonitae-complex-iii/)
Philippine skinks of the genus Brachymeles are a fascinating group with varying degrees of limb and digit loss that are thought to help them adapt to specific challenges in their environment. Work lead by Dr. Cameron Siler has discovered many cryptic species within Brachymeles, with additional evidence that more cryptic species are present within the B. bonitae complex. This project reports formal description of a new species of fossorial skink within the Brachymeles bonitae complex found on Tablas Island in the Philippines, based on collections made over 50 years ago. This work is near and dear to my heart, at it was the first scientific paper I contributed to. I appreciate Dr. Siler giving me and the other undergraduates on this project an opportunity to publish!